### ISSUE TITLE
Tick strings can be with many brackets

### ISSUE THREAD

**Issue by Alexey-T** [silentTee/sublimetext3-perl6-syntax#11]
```
#`( )
#`[ ]
#`{ }
#`< >
```
Also brackets can be nested!!

**Comment by silentTee** [comment]
included support for the different bracket types, but I'm struggling to figure out how to support nested brackets. Traditional recursive regex via (?R) does not seem to be supported. Currently exploring the idea of recursive context pushes...

**Comment by silentTee** [comment]
Figured out recursive contexts, basic solution implemented!
